feat: add path filter template

diff --git a/templates/common.yml b/templates/common.yml
--- a/templates/common.yml
+++ b/templates/common.yml
@@ -316,3 +316,88 @@
   artifacts:
     reports:
       dotenv: semantic.env
+
+.path-filter:
+  image: msclock/pre-commit:2023-08-10T09-27-52Z
+  variables:
+    WORKING_DIRECTORY: .
+    REF: ''
+    BASE: ''
+    FILTERS: ''
+    LIST_FILES: none
+    INITIAL_FETCH_DEPTH: '100'
+  before_script:
+    - |
+      apt update && apt install jq -y
+  script:
+    - |
+      # set -x
+
+      # Set the working directory if provided
+      if [[ -n "$WORKING_DIRECTORY" ]]; then
+        cd "$WORKING_DIRECTORY"
+      fi
+
+      # Checkout the specified ref
+      if [[ -n "$REF" ]]; then
+        git checkout "$REF"
+      fi
+
+      if [[ -z "$FILTERS" ]]; then
+        echo "Invalid FILTERS configuration."
+        exit 1
+      fi
+
+      if [[ -n "$BASE" ]]; then
+        all_changes_output=$(git diff --no-renames --name-status "$BASE"..HEAD)
+      else
+        all_changes_output=$(git diff --no-renames --name-status HEAD)
+      fi
+
+      # expose to dotenv artifact
+      function expose() {
+        expose_key=$1
+        content=$(echo -e "$2" | tr -s '\n')
+
+        if [ "$LIST_FILES" = "csv" ]; then
+          content=$(echo -e "$content" | awk '{print "\""$2"\""}'| paste -sd ",")
+        elif [ "$LIST_FILES" = "json" ]; then
+          content=$(echo -e "$content" | awk '{print $2}' | jq -R . | jq -s .)
+        elif [ "$LIST_FILES" = "shell" ]; then
+          content=$(echo -e "$content" | awk '{print $2}' | xargs -I{} echo -e "{}")
+        elif [ "$LIST_FILES" = "escape" ]; then
+          content=$(echo -e "$content" | awk '{print $2}' | xargs -I{} echo -e "{}" | sed 's/[^a-zA-Z0-9,._+:@%/-]/\\&/g')
+        fi
+
+        echo "$expose_key='${content//$'\n'/\\n}'" >> filter.env
+      }
+
+      echo "all_changes_output: $all_changes_output"
+      echo "raw_all_changes_output='${all_changes_output//$'\n'/\\n}'" > filter.env
+      expose "all_changes_output" "$all_changes_output"
+
+      keys=$(echo "$FILTERS" | jq -r "keys[]")
+      for category in $keys; do
+        values=$(echo "$FILTERS" | jq -r ".$category")
+        # echo -e "values: ${values}"
+        readarray -t _values <<< "$(echo -e "$values" | jq -r ".[]")"
+        # echo -e "_values: ${_values[@]}"
+        changes=""
+        for pattern in "${_values[@]}"; do
+          # echo -e "pattern: $pattern"
+          filtered=""
+          while IFS= read -r line; do
+            filename=$(echo "$line" | awk '{print $2}')
+            if echo "$filename" | grep -Pq "$pattern"; then
+              filtered+="$line\n"
+            fi
+          done <<< "$all_changes_output"
+
+          changes+="$filtered"
+        done
+
+        expose "$category" "$changes"
+      done
+  artifacts:
+    reports:
+      dotenv: filter.env
