perf: add schedule pipeline actions for release
set RELEASE_POST_PIPELINE_TYPE to empty on default

diff --git a/templates/Common.gitlab-ci.yml b/templates/Common.gitlab-ci.yml
--- a/templates/Common.gitlab-ci.yml
+++ b/templates/Common.gitlab-ci.yml
@@ -22,3 +22,23 @@ include:
     git config --global user.name ${CI_USRE_NAME:-gitlab-ci[bot]}
     git config --global user.email ${CI_USER_EMAIL:-noreply+gitlab-ci[bot]@${CI_SERVER_HOST}}
     git config --global lfs.locksverify true
+
+# @Description create pipeline, if pipeline ref SCHEDULE_REF is set
+.schedule_pipeline:
+  image: msclock/semantic-release:2023-09-07T07-45-23Z
+  variables:
+    SCHEDULE_REF: ''
+  script:
+    - !reference [.security_check_sensible, script]
+    - |
+      if [[ -z "$SCHEDULE_REF" ]]; then
+        echo "Invalid pipeline ref=$SCHEDULE_REF, must be set properly" >> /dev/stderr
+        exit 1
+      fi
+
+      response=$(curl -sw '\n%{http_code}\n' --header "PRIVATE-TOKEN: ${GITLAB_TOKEN:-$CI_JOB_TOKEN}" \
+          --request POST "$CI_API_V4_URL/projects/$CI_PROJECT_ID/pipeline?ref=$SCHEDULE_REF")
+      if [[ "$(echo -e "$response" | tail -n 1)" != "201" ]]; then
+        echo -e "Failed to create pipeline, response:\n$response" >> /dev/stderr
+        exit 1
+      fi
diff --git a/templates/Release.gitlab-ci.yml b/templates/Release.gitlab-ci.yml
--- a/templates/Release.gitlab-ci.yml
+++ b/templates/Release.gitlab-ci.yml
@@ -1,5 +1,6 @@
 include:
   - remote: https://gitlab.com/msclock/gitlab-ci-templates/-/raw/v2.0.0/templates/Rules.gitlab-ci.yml
+  - local: /templates/Common.gitlab-ci.yml
 
 # @Description template for release publish
 .release:
@@ -99,3 +100,36 @@ include:
   artifacts:
     reports:
       dotenv: semantic.env
+
+# @Description post release pipeline, default to run tag post pipeline
+.post_pipelilne:
+  extends:
+    - .schedule_pipeline
+  rules:
+    - !reference [.rules, Skip Release Commits]
+    - if: |
+        ( $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH ||
+        $CI_COMMIT_REF_NAME =~ /^(alpha|beta)$/ ) &&
+        $RELEASE_POST_PIPELINE_TYPE
+  variables:
+    RELEASE_POST_PIPELINE_TYPE: '' # '', 'tag' or 'branch'
+  before_script:
+    - |
+      if [[ -z "$new_release_version" ]]; then
+        echo "Skip post release pipeline because new_release_version is not set" >> /dev/stderr
+        exit 0
+      fi
+
+      if [[ "$RELEASE_POST_PIPELINE_TYPE" == "tag" ]]; then
+        export SCHEDULE_REF="v$new_release_version"
+      fi
+
+      if [[ "$RELEASE_POST_PIPELINE_TYPE" == "branch" ]]; then
+        if [[ -z "$CI_COMMIT_BRANCH" ]]; then
+          echo "Invalid schedule pipeline, and CI_COMMIT_BRANCH must be set if RELEASE_POST_PIPELINE_TYPE is branch" >> /dev/stderr
+          exit 1
+        fi
+        export SCHEDULE_REF="$CI_COMMIT_BRANCH"
+      fi
+
+      echo "Ready to schedule pipeline type: $RELEASE_POST_PIPELINE_TYPE, ref: $SCHEDULE_REF"
