perf: script model
Signed-off-by: msclock <msclock@qq.com>

diff --git a/templates/Make-Changes.gitlab-ci.yml b/templates/Make-Changes.gitlab-ci.yml
--- a/templates/Make-Changes.gitlab-ci.yml
+++ b/templates/Make-Changes.gitlab-ci.yml
@@ -1,7 +1,71 @@
-# This presents a template to make changes to codebase using the native
-# gitlab restapi.
+# This presents templates to make changes to codebase.
 #
 # To configure the template refers to the variables section.
+
+# @Description scripts for make_changes
+.make_changes::scripts:
+  Security Check Sensible: !reference [.security_check_sensible, script]
+  Make Changes Git: !reference [.common_git::template, script]
+  Detect Changes: |-
+    _detect_pattern='[^?]'
+    if [[ $DETECT_CHANGES_ADD =~ ^(1|true)$ ]]; then
+      _detect_pattern='.'
+    fi
+
+    changes=$(git status -s | grep -E "^"$_detect_pattern"+$")
+    if [[ -z "$changes" ]]; then
+      echo "Working tree clean. Nothing to make changes.";
+      exit 0
+    fi
+  Commit Changes: |-
+    if [[ -n "$MAKE_CHANGES_ON_PR" ]]; then
+      temp_branch=changes_on_pr_${CI_COMMIT_SHA:0:12}
+      git checkout -B "$temp_branch" --
+    fi
+
+    git add -u .
+    _title=$(eval "echo ${MAKE_CHANGES_MSG:-ci: automated commit changes from CI job}")
+    _body=$(eval "echo ${MAKE_CHANGES_MSG_BODY}")
+    git commit -m "$_title" -m "$_body" -m "job url: $CI_JOB_URL"
+    if [[ -n "$MAKE_CHANGES_ON_PR" ]]; then
+      git push origin "$temp_branch"
+      curl --header "PRIVATE-TOKEN: ${GITLAB_TOKEN:-$CI_JOB_TOKEN}" \
+        --request POST "$CI_API_V4_URL/projects/$CI_PROJECT_ID/merge_requests" \
+        --form "source_branch=$temp_branch" \
+        --form "target_branch=$CI_COMMIT_REF_NAME" \
+        --form "title=PR from $temp_branch"
+    elif [[ -n "$CI_COMMIT_BRANCH" ]]; then
+      git push origin HEAD:"$CI_COMMIT_BRANCH"
+    elif [[ -n "$CI_MERGE_REQUEST_IID" ]]; then
+      git push origin HEAD:"$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"
+    fi
+  Check Exit: |-
+    echo "Check and exit the current pipeline..."
+    case $MAKE_CHANGES_FINISH in
+      error)
+        echo "Finish with error the current pipeline..."
+        exit 1
+        ;;
+      skip)
+        echo "Finish with skip the current pipeline..."
+        curl --header "PRIVATE-TOKEN: ${GITLAB_TOKEN:-$CI_JOB_TOKEN}" \
+          --request POST "$CI_API_V4_URL/projects/$CI_PROJECT_ID/pipelines/${CI_PIPELINE_ID}/cancel"
+        ;;
+      *)
+        echo "Finish with success the current pipeline..."
+        exit 0
+        ;;
+    esac
+
+# @Description steps constraints template for make_changes
+.make_changes::template:
+  extend: .make_changes::scripts
+  script:
+    - !reference [.make_changes::scripts, Security Check Sensible]
+    - !reference [.make_changes::scripts, Make Changes Git]
+    - !reference [.make_changes::scripts, Detect Changes]
+    - !reference [.make_changes::scripts, Commit Changes]
+    - !reference [.make_changes::scripts, Check Exit]
 
 # @Description make changes on codebase
 .make_changes:
@@ -10,55 +74,16 @@
     MAKE_CHANGES_MSG: ''
     # Optional. Allow customization of the commit body.
     MAKE_CHANGES_MSG_BODY: ''
-    # Optional. When set, creates a temporary branch and pushes the changes to it, along with creating a merge request for code review.
+    # Creates a temporary branch and pushes the changes to it,
+    # along with creating a merge request for code review.
+    # - `true`: creates a temporary branch and pushes the changes to it,
+    # - `false`: skips the temporary branch and pushes the changes to it.
     MAKE_CHANGES_ON_PR: ''
-    # Optional. Controls the exit behavior of the CI job. `skip`: the current pipeline will be skipped. `error`: exits code 1. Leave blank to exits 0.
+    # Controls the exit behavior of the CI job.
+    # - `skip`: the current pipeline will be skipped.
+    # - `error`: exits with code 1.
+    # - `''`(Default): exits 0.
     MAKE_CHANGES_FINISH: ''
     # Optional. Controls if the added files are detected as changes.
     DETECT_CHANGES_ADD: 1
-  script:
-    - !reference [.security_check_sensible, script]
-    - !reference [.security_git_config, script]
-    - |
-      _detect_pattern='[^?]'
-      if [[ $DETECT_CHANGES_ADD =~ ^(1|true)$ ]]; then
-        _detect_pattern='.'
-      fi
-
-      if [[ -n "$(git status -s | grep -E "^"$_detect_pattern"+$")" ]]; then
-
-        if [[ -n "$MAKE_CHANGES_ON_PR" ]]; then
-          temp_branch=changes_on_pr_${CI_COMMIT_SHA:0:12}
-          git checkout -B "$temp_branch" --
-        fi
-
-        git add -u .
-        _title=$(eval "echo ${MAKE_CHANGES_MSG:-ci: automated commit changes from CI job}")
-        _body=$(eval "echo ${MAKE_CHANGES_MSG_BODY}")
-        git commit -m "$_title" -m "$_body" -m "job url: $CI_JOB_URL"
-        if [[ -n "$MAKE_CHANGES_ON_PR" ]]; then
-          git push origin "$temp_branch"
-          curl --header "PRIVATE-TOKEN: ${GITLAB_TOKEN:-$CI_JOB_TOKEN}" \
-            --request POST "$CI_API_V4_URL/projects/$CI_PROJECT_ID/merge_requests" \
-            --form "source_branch=$temp_branch" \
-            --form "target_branch=$CI_COMMIT_REF_NAME" \
-            --form "title=PR from $temp_branch"
-        elif [[ -n "$CI_COMMIT_BRANCH" ]]; then
-          git push origin HEAD:"$CI_COMMIT_BRANCH"
-        elif [[ -n "$CI_MERGE_REQUEST_IID" ]]; then
-          git push origin HEAD:"$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"
-        fi
-      else
-        echo "Working tree clean. Nothing to make changes.";
-        exit 0
-      fi
-
-      case $MAKE_CHANGES_FINISH in
-        error) exit 1 ;;
-        skip)
-          echo "Finish with skip the current pipeline..."
-          curl --header "PRIVATE-TOKEN: ${GITLAB_TOKEN:-$CI_JOB_TOKEN}" \
-            --request POST "$CI_API_V4_URL/projects/$CI_PROJECT_ID/pipelines/${CI_PIPELINE_ID}/cancel"
-          ;;
-        *) exit 0 ;;
-      esac
+  script: !reference [.make_changes::template, script]
diff --git a/templates/Path-Filter.gitlab-ci.yml b/templates/Path-Filter.gitlab-ci.yml
--- a/templates/Path-Filter.gitlab-ci.yml
+++ b/templates/Path-Filter.gitlab-ci.yml
@@ -1,6 +1,115 @@
-# This presents a template to detect changes on codebase
+# This presents templates to detect changes on codebase
 #
 # To configure the template refers to the variables section.
+
+.path_filter::scripts:
+  Security Check Sensible: !reference [.security_check_sensible, script]
+  Path Filter Git: !reference [.common_git::template, script]
+  To Working Directory: |-
+    echo "Change the working directory to $WORKING_DIRECTORY"
+    if [[ -n "$WORKING_DIRECTORY" ]]; then
+      cd "$WORKING_DIRECTORY"
+    fi
+  Verify Filters: |-
+    echo "Verify filters: $FILTERS is set"
+    if [[ -z "$FILTERS" ]]; then
+      echo "Invalid FILTERS configuration."
+      exit 1
+    fi
+  Detect Changes: |-
+    echo "Detect changes. If in pr, detect changes against pr target branch"
+    if [[ -n "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" ]]; then
+      git fetch origin --force $CI_MERGE_REQUEST_TARGET_BRANCH_NAME:$CI_MERGE_REQUEST_TARGET_BRANCH_NAME
+      all_changes_output=$(git diff --no-renames --name-status $CI_MERGE_REQUEST_TARGET_BRANCH_NAME)
+    else
+      # Ensure on the branch we want to detect changes against
+      git branch -D $REF || true
+      git fetch origin --depth=$INITIAL_FETCH_DEPTH --force $REF
+      git checkout --force "$REF"
+
+      if [[ $BASE == $REF ]]; then
+        if [[ $CI_COMMIT_BEFORE_SHA != "0000000000000000000000000000000000000000" ]] && git rev-list $REF | grep $CI_COMMIT_BEFORE_SHA > /dev/null; then
+          _against_base=$CI_COMMIT_BEFORE_SHA
+        else
+          _against_base=$(git rev-parse HEAD~1)
+        fi
+      else
+        git branch -D $BASE || true
+        git fetch origin --depth=$INITIAL_FETCH_DEPTH --force "$BASE":$CI_JOB_ID
+        _against_base=$(git merge-base $CI_JOB_ID $REF)
+      fi
+
+      all_changes_output=$(git diff --no-renames --name-status $_against_base..$REF)
+      git branch -D $CI_JOB_ID $BASE || true
+    fi
+    echo -e "all_changes_output:\n$all_changes_output"
+  Expose raw_all_changes_output: |-
+    echo "Expose raw_all_changes_output to dotenv"
+    echo "raw_all_changes_output='${all_changes_output//$'\n'/\\n}'" > filter.env
+  Define Expose: |-
+    echo "Define expose function to set dotenv"
+    function expose() {
+      expose_key=$1
+      content=${2%'\n'} # trim the newline
+
+      case "$LIST_FILES" in
+        csv)
+          content=$(echo -e "$content" | awk '{print "\""$2"\""}'| paste -sd ",")
+          ;;
+        json)
+          content=$(echo -e "$content" | awk '{print $2}' | jq -R . | jq -s .)
+          ;;
+        shell)
+          content=$(echo -e "$content" | awk '{print $2}' | xargs -I{} echo -e "{}")
+          ;;
+        escape)
+          content=$(echo -e "$content" | awk '{print $2}' | xargs -I{} echo -e "{}" | sed 's/[^a-zA-Z0-9,._+:@%/-]/\\&/g')
+          ;;
+      esac
+
+      echo "$expose_key=${content//$'\n'/\\n}" >> filter.env # escape new line into dotenv
+    }
+  Expose all_changes_output: |-
+    echo "Expose all_changes_output to dotenv"
+    expose "all_changes_output" "$all_changes_output"
+  Expose Based On Filters: |-
+    echo "Expose Based On Filters: $FILTERS to dotenv"
+    keys=$(echo "$FILTERS" | jq -r "keys[]")
+    declare -A patterns_map
+    for category in $keys; do
+      patterns_map["$category"]=$(echo -e "$FILTERS" | jq -r ".$category[]")
+    done
+
+    for category in "${!patterns_map[@]}"; do
+      patterns="${patterns_map[$category]}"
+      echo -e "patterns from $category:\n${patterns[@]}"
+      changes=""
+      while IFS= read -r line; do
+        filename=$(echo "$line" | awk '{print $2}')
+        for pattern in $patterns; do
+          if echo "$filename" | grep -Pq "$pattern"; then
+            changes+="$line\n"
+            break
+          fi
+        done
+      done <<< "$all_changes_output"
+
+      echo -e "changes from $category:\n$changes"
+      expose "$category" "$changes"
+    done
+
+# @Description steps constraints template
+.path_filter::template:
+  script:
+    - !reference [.path_filter::scripts, Security Check Sensible]
+    - !reference [.path_filter::scripts, Path Filter Git]
+    - !reference [.path_filter::scripts, To Working Directory]
+    - !reference [.path_filter::scripts, Verify Filters]
+    - !reference [.path_filter::scripts, Detect Changes]
+    - !reference [.path_filter::scripts, Expose raw_all_changes_output]
+    - !reference [.path_filter::scripts, Define Expose]
+    - !reference [.path_filter::scripts, Expose all_changes_output]
+    - !reference [.path_filter::scripts, Expose Based On Filters]
 
 # @Description template for path changes based on git subcommand diff
 .path_filter:
@@ -44,96 +153,7 @@
     LIST_FILES: none
     # Initial fetch depth for detecting changes
     INITIAL_FETCH_DEPTH: '30'
-  script:
-    - !reference [.security_git_config, script]
-    - |
-      # Set the working directory if provided
-      if [[ -n "$WORKING_DIRECTORY" ]]; then
-        cd "$WORKING_DIRECTORY"
-      fi
-
-      if [[ -z "$FILTERS" ]]; then
-        echo "Invalid FILTERS configuration."
-        exit 1
-      fi
-
-      # Detect changes
-      # If in pr, detect changes against pr target branch
-      if [[ -n "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" ]]; then
-        git fetch origin --force $CI_MERGE_REQUEST_TARGET_BRANCH_NAME:$CI_MERGE_REQUEST_TARGET_BRANCH_NAME
-        all_changes_output=$(git diff --no-renames --name-status $CI_MERGE_REQUEST_TARGET_BRANCH_NAME)
-      else
-        # Ensure on the branch we want to detect changes against
-        git branch -D $REF || true
-        git fetch origin --depth=$INITIAL_FETCH_DEPTH --force $REF
-        git checkout --force "$REF"
-
-        if [[ $BASE == $REF ]]; then
-          if [[ $CI_COMMIT_BEFORE_SHA != "0000000000000000000000000000000000000000" ]] && git rev-list $REF | grep $CI_COMMIT_BEFORE_SHA > /dev/null; then
-            _against_base=$CI_COMMIT_BEFORE_SHA
-          else
-            _against_base=$(git rev-parse HEAD~1)
-          fi
-        else
-          git branch -D $BASE || true
-          git fetch origin --depth=$INITIAL_FETCH_DEPTH --force "$BASE":$CI_JOB_ID
-          _against_base=$(git merge-base $CI_JOB_ID $REF)
-        fi
-
-        all_changes_output=$(git diff --no-renames --name-status $_against_base..$REF)
-        git branch -D $CI_JOB_ID $BASE || true
-      fi
-
-      # Expose to dotenv artifact
-      function expose() {
-        expose_key=$1
-        content=${2%'\n'} # trim the newline
-
-        case "$LIST_FILES" in
-          csv)
-            content=$(echo -e "$content" | awk '{print "\""$2"\""}'| paste -sd ",")
-            ;;
-          json)
-            content=$(echo -e "$content" | awk '{print $2}' | jq -R . | jq -s .)
-            ;;
-          shell)
-            content=$(echo -e "$content" | awk '{print $2}' | xargs -I{} echo -e "{}")
-            ;;
-          escape)
-            content=$(echo -e "$content" | awk '{print $2}' | xargs -I{} echo -e "{}" | sed 's/[^a-zA-Z0-9,._+:@%/-]/\\&/g')
-            ;;
-        esac
-
-        echo "$expose_key=${content//$'\n'/\\n}" >> filter.env # escape new line into dotenv
-      }
-
-      echo -e "all_changes_output:\n$all_changes_output"
-      echo "raw_all_changes_output='${all_changes_output//$'\n'/\\n}'" > filter.env
-      expose "all_changes_output" "$all_changes_output"
-
-      keys=$(echo "$FILTERS" | jq -r "keys[]")
-      declare -A patterns_map
-      for category in $keys; do
-        patterns_map["$category"]=$(echo -e "$FILTERS" | jq -r ".$category[]")
-      done
-
-      for category in "${!patterns_map[@]}"; do
-        patterns="${patterns_map[$category]}"
-        echo -e "patterns from $category:\n${patterns[@]}"
-        changes=""
-        while IFS= read -r line; do
-          filename=$(echo "$line" | awk '{print $2}')
-          for pattern in $patterns; do
-            if echo "$filename" | grep -Pq "$pattern"; then
-              changes+="$line\n"
-              break
-            fi
-          done
-        done <<< "$all_changes_output"
-
-        echo -e "changes from $category:\n$changes"
-        expose "$category" "$changes"
-      done
+  script: !reference [.path_filter::template, script]
   artifacts:
     reports:
       dotenv: filter.env
diff --git a/templates/Release.gitlab-ci.yml b/templates/Release.gitlab-ci.yml
--- a/templates/Release.gitlab-ci.yml
+++ b/templates/Release.gitlab-ci.yml
@@ -15,6 +15,90 @@ variables:
   # and the value can be '', 'tag' or 'branch'
   RELEASE_POST_PIPELINE_TYPE: ''
 
+.release::scripts:
+  Security Check Sensible: !reference [.security_check_sensible, script]
+  Release Git: !reference [.common_git::template, script]
+  Set Npm Source: |-
+    echo "Configuring NPM_SOURCE: $NPM_SOURCE when it is set"
+    if [[ -n "$NPM_SOURCE" ]]; then
+      npm config set registry "$NPM_SOURCE"
+      npm get registry
+    fi
+  Setup Semantic Release: |-
+    echo "Install semantic release plugins..." >> /dev/stderr
+    npm install -g semantic-release \
+      @semantic-release/release-notes-generator \
+      @semantic-release/gitlab $RELEASE_EXTRA_PLUGINS
+  Generate Preset Releaserc If Needed: |-
+    echo "Generate preset releaserc when USING_PRESET_RELEASERC: $_PRESET_RELEASERC_FILE is set"
+    if [[ -n "$USING_PRESET_RELEASERC" ]]; then
+      echo "Generating preset releaserc $_PRESET_RELEASERC_FILE..."
+      echo "$_PRESET_RELEASERC_CONFIG" > "$_PRESET_RELEASERC_FILE"
+    fi
+  Update Local Tags: |-
+    echo "Update the local tags" >> /dev/stderr
+    git fetch --tags --force
+  Info Tags Now: |-
+    echo "Info local and remote tags now" >> /dev/stderr
+    if [[ $CI_DEBUG_TRACE =~ ^(1|true)$ ]]; then
+      echo "Local tags:" >> /dev/stderr
+      git tag -l
+      echo "Remote tags:" >> /dev/stderr
+      git ls-remote --tags origin
+    fi
+  Delete Not Existing Local Tags: |-
+    echo "Delete the local tags that no longer exist on the remote repository" >> /dev/stderr
+    git fetch origin --prune --prune-tags
+  Remove Conflicting Release And Tags: |-
+    echo "Remove conflicting release and delete the existing tag and release if possible"
+    if [[ -n "$OVERRIDE_RELEASE" ]]; then
+      _dry_run_output=$(semantic-release -d --ci)
+      _verify_version=$(echo "$_dry_run_output" | grep -oP "(?<=Skip ).+(?= tag creation in dry-run mode)") || true
+      if [[ $(git tag -l) =~ (^|[[:space:]])"$_verify_version"($|[[:space:]]) ]]; then
+        echo "Found and delete conflicting tag $_verify_version"
+        git push origin :refs/tags/"$_verify_version" || true
+        git tag -d "$_verify_version"
+
+        echo "Delete release if possible"
+        curl --header "PRIVATE-TOKEN: ${GITLAB_TOKEN:-$CI_JOB_TOKEN}" \
+          --request DELETE "$CI_API_V4_URL/projects/$CI_PROJECT_ID/releases/$_verify_version" || true
+      else
+        echo "No conflicting release found"
+      fi
+    fi
+  Run Semantic Release: |-
+    echo "Run semantic release" >> /dev/stderr
+    if [[ -z "$SEMANTIC_RELEASE_OPTIONS" ]]; then
+      _release_output=$(semantic-release)
+    else
+      echo "Be careful!! CLI arguments take precedence over options configured in the configuration file"
+      _release_output=$(semantic-release "$SEMANTIC_RELEASE_OPTIONS")
+    fi
+    echo -e "Semantic Release Output:\n$_release_output"
+  Expose Release Version: |-
+    echo "Expose the release version to semantic.env" >> /dev/stderr
+    new_release_version=$(echo "$_release_output" | grep -oP "(?<=Published release ).+(?= on)") || true
+    echo "new_release_version=$new_release_version" >> semantic.env
+  Clean Up Preset Releaserc: |-
+    echo "Clean up preset releaserc when USING_PRESET_RELEASERC: $_PRESET_RELEASERC_FILE is set"
+    if [[ -n "$USING_PRESET_RELEASERC" && -f "$_PRESET_RELEASERC_FILE" ]]; then
+      rm -f "$_PRESET_RELEASERC_FILE"
+    fi
+
+.release::template:
+  script:
+    - !reference [.release::scripts, Security Check Sensible]
+    - !reference [.release::scripts, Release Git]
+    - !reference [.release::scripts, Set Npm Source]
+    - !reference [.release::scripts, Setup Semantic Release]
+    - !reference [.release::scripts, Generate Preset Releaserc If Needed]
+    - !reference [.release::scripts, Update Local Tags]
+    - !reference [.release::scripts, Info Tags Now]
+    - !reference [.release::scripts, Delete Not Existing Local Tags]
+    - !reference [.release::scripts, Remove Conflicting Release And Tags]
+    - !reference [.release::scripts, Run Semantic Release]
+    - !reference [.release::scripts, Expose Release Version]
+
 # @Description template for release publish
 .release:
   image: msclock/semantic-release:2023-11-24T06-11-45Z
@@ -127,72 +211,43 @@ variables:
     GITLAB_PREFIX: /api/v4
     # Optional. The instance of gitlab
     GITLAB_URL: $CI_SERVER_URL
-  script:
-    - !reference [.security_check_sensible, script]
-    - |
-      if [[ -n "$NPM_SOURCE" ]]; then
-        echo "Configuring npm registry from $NPM_SOURCE"
-        npm config set registry "$NPM_SOURCE"
-        npm get registry
-      fi
-
-      echo "Install semantic release plugins..." >> /dev/stderr
-      npm install -g semantic-release \
-        @semantic-release/release-notes-generator \
-        @semantic-release/gitlab $RELEASE_EXTRA_PLUGINS
-    - !reference [.security_git_config, script]
-    - |
-      if [[ -n "$USING_PRESET_RELEASERC" ]]; then
-        echo "Generating preset releaserc $_PRESET_RELEASERC_FILE..."
-        echo "$_PRESET_RELEASERC_CONFIG" > "$_PRESET_RELEASERC_FILE"
-      fi
-
-      echo "Update the local tags" >> /dev/stderr
-      git fetch --tags --force
-
-      if [[ $CI_DEBUG_TRACE =~ ^(1|true)$ ]]; then
-        echo "Local tags:" >> /dev/stderr
-        git tag -l
-        echo "Remote tags:" >> /dev/stderr
-        git ls-remote --tags origin
-      fi
-
-      echo "Delete the local tags that no longer exist on the remote repository" >> /dev/stderr
-      git fetch origin --prune --prune-tags
-
-      echo "Detect conflicting release and delete the existing tag and release if possible"
-      if [[ -n "$OVERRIDE_RELEASE" ]]; then
-        _dry_run_output=$(semantic-release -d --ci)
-        _verify_version=$(echo "$_dry_run_output" | grep -oP "(?<=Skip ).+(?= tag creation in dry-run mode)") || true
-        if [[ $(git tag -l) =~ (^|[[:space:]])"$_verify_version"($|[[:space:]]) ]]; then
-          echo "Found and delete conflicting tag $_verify_version"
-          git push origin :refs/tags/"$_verify_version" || true
-          git tag -d "$_verify_version"
-
-          echo "Delete release if possible"
-          curl --header "PRIVATE-TOKEN: ${GITLAB_TOKEN:-$CI_JOB_TOKEN}" \
-              --request DELETE "$CI_API_V4_URL/projects/$CI_PROJECT_ID/releases/$_verify_version" || true
-        else
-          echo "No conflicting release found"
-        fi
-      fi
-
-      if [[ -z "$SEMANTIC_RELEASE_OPTIONS" ]]; then
-        _release_output=$(semantic-release)
-      else
-        echo "Be careful!! CLI arguments take precedence over options configured in the configuration file"
-        _release_output=$(semantic-release "$SEMANTIC_RELEASE_OPTIONS")
-      fi
-      echo -e "Semantic Release Output:\n$_release_output"
-      new_release_version=$(echo "$_release_output" | grep -oP "(?<=Published release ).+(?= on)") || true
-      echo "new_release_version=$new_release_version" >> semantic.env
+  script: !reference [.release::template, script]
   after_script:
     # Finally, remove the preset releaserc file
-    - |
-      [[ -n "$USING_PRESET_RELEASERC" && -f "$_PRESET_RELEASERC_FILE" ]] && rm -f "$_PRESET_RELEASERC_FILE"
+    - !reference [.release::scripts, Clean Up Preset Releaserc]
   artifacts:
     reports:
       dotenv: semantic.env # Expose the new release version to dotenv
+
+.post_pipeline::scripts:
+  Skip Non-Release Commits: |-
+    echo "Skip post release pipeline because new_release_version is not set" >> /dev/stderr
+    if [[ -z "$new_release_version" ]]; then
+      exit 0
+    fi
+  Schedule Pipeline For Tag: |-
+    echo "Schedule pipeline for tag $new_release_version" >> /dev/stderr
+    if [[ "$RELEASE_POST_PIPELINE_TYPE" == "tag" ]]; then
+      export SCHEDULE_REF="v$new_release_version"
+    fi
+  Schedule Pipeline For Branch: |-
+    if [[ "$RELEASE_POST_PIPELINE_TYPE" == "branch" ]]; then
+      if [[ -z "$CI_COMMIT_BRANCH" ]]; then
+        echo "Invalid schedule pipeline, and CI_COMMIT_BRANCH must be set if RELEASE_POST_PIPELINE_TYPE is branch" >> /dev/stderr
+        exit 1
+      fi
+      export SCHEDULE_REF="$CI_COMMIT_BRANCH"
+    fi
+  Info Post Schedule Pipeline: |-
+    echo "Ready to schedule pipeline type: $RELEASE_POST_PIPELINE_TYPE, ref: $SCHEDULE_REF"
+
+# @Description steps constraints template
+.post_pipeline::template:
+  script:
+    - !reference [.post_pipeline::scripts, Skip Non-Release Commits]
+    - !reference [.post_pipeline::scripts, Schedule Pipeline For Tag]
+    - !reference [.post_pipeline::scripts, Schedule Pipeline For Branch]
+    - !reference [.post_pipeline::scripts, Info Post Schedule Pipeline]
 
 # @Description post release pipeline, default to run tag post pipeline
 .post_pipelilne:
@@ -205,23 +260,4 @@ variables:
         $CI_COMMIT_REF_NAME =~ /^(alpha|beta|next|next-major)$/ ||
         $CI_COMMIT_REF_NAME =~ /^+([0-9])?(.{+([0-9]),x}).x$/ ) &&
         $RELEASE_POST_PIPELINE_TYPE
-  before_script:
-    - |
-      if [[ -z "$new_release_version" ]]; then
-        echo "Skip post release pipeline because new_release_version is not set" >> /dev/stderr
-        exit 0
-      fi
-
-      if [[ "$RELEASE_POST_PIPELINE_TYPE" == "tag" ]]; then
-        export SCHEDULE_REF="v$new_release_version"
-      fi
-
-      if [[ "$RELEASE_POST_PIPELINE_TYPE" == "branch" ]]; then
-        if [[ -z "$CI_COMMIT_BRANCH" ]]; then
-          echo "Invalid schedule pipeline, and CI_COMMIT_BRANCH must be set if RELEASE_POST_PIPELINE_TYPE is branch" >> /dev/stderr
-          exit 1
-        fi
-        export SCHEDULE_REF="$CI_COMMIT_BRANCH"
-      fi
-
-      echo "Ready to schedule pipeline type: $RELEASE_POST_PIPELINE_TYPE, ref: $SCHEDULE_REF"
+  before_script: !reference [.post_pipeline::template, script]
